### ISSUE TITLE
learn what a loop is

### ISSUE THREAD

**Issue by AndreiSva** [rutkuli/spoofer#1]
youtube is a good resource

**Comment by rutkuli** [comment]
1. This is not an place right for this  2. Thats an frosherowski's broplem

**Comment by rutkuli** [comment]
And I will say that even though this does not concern me, so I will take this as a note.

**Comment by ImFrosher** [comment]
hospital is also good place for you

**Comment by AndreiSva** [comment]
You are wasting ram with hundreds of useless variables

**Comment by ImFrosher** [comment]
you are wasting your time writing this trash comments

**Comment by AndreiSva** [comment]
Haha I was expecting some toxicity but this is off the charts
